### ISSUE TITLE
Idea: Add a NPX script

### ISSUE THREAD

**Issue by sampoder** [lachlanjc/next-theme-starter#1]
You know what would be so cool... if I could go `npx @lachlanjc/next-theme-starter` and it'd set this all up for me

Bit like create-next-app, you know?

**Comment by lachlanjc** [comment]
That sure would be amazing. Thanks for the idea! If you want to do this, go for it, but otherwise I will definitely be thinking about it/hope to get to it soon.

**Comment by sampoder** [comment]
was thinking a bit more bout this, maybe adding it to the examples folder used by `create-next-app`

**Comment by sampoder** [comment]
Here are the instructions to do that: https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

**Comment by sampoder** [comment]
I could do it if you like

**Comment by sampoder** [comment]
Came back to this, I'm going to make a PR to use create next app's --example flag
